{% set name = "esparto" %}
{% set version = "4.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/esparto-{{ version }}.tar.gz
  sha256: 1bcb6e8acbd9b8151615eba79ad3acfb5cf2954379ab0f754d64e7c252da81b9

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=0.12
    - python {{ python_min }}
  run:
    - beautifulsoup4 >=4.7
    - dataclasses
    - jinja2 >=2.10.1
    - markdown >=3.1
    - python >={{ python_min }}
    - pyyaml >=5.1

test:
  imports:
    - esparto
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://domvwt.github.io/esparto
  summary: Data driven report builder for the PyData ecosystem.
  license: MIT
  license_file: LICENSE
  doc_url: https://domvwt.github.io/esparto/
  dev_url: https://github.com/domvwt/esparto

extra:
  recipe-maintainers:
    - domvwt
